### ISSUE TITLE
Code Help

### ISSUE THREAD

**Issue by kartik4949** [tlegx/hangman_terminal#1]
Hi,
i can help you refactor this!

**Comment by tlegx** [comment]
Hi,
Thank you for your help on my code!
If you want to make changes, feel free to fork this repository and open a pull request.
If this was not what you meant or you want to further discuss about this, please send me an email to the address provided in my profile's README.
Once again, thank you so much for reaching out :)

**Comment by kartik4949** [comment]
Hi,
sure let me fork this and push changes with refactor and some optimizations :)
